// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // SUBSTITUA com as configurações do Firebase Console
  // Acesse: https://console.firebase.google.com/
  // Projeto > Configurações > Seus apps > Android

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVOMmidqPOK4rjstwHKa0nzS-d0JsVJIc',
    appId: '1:1016473191297:android:9cfc37dda5db30a1eade80',
    messagingSenderId: '1016473191297',
    projectId: 'treteste-b0b5b',
    storageBucket: 'treteste-b0b5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVOMmidqPOK4rjstwHKa0nzS-d0JsVJIc',
    appId: '1:1016473191297:ios:XXXXX',
    messagingSenderId: '1016473191297',
    projectId: 'treteste-b0b5b',
    storageBucket: 'treteste-b0b5b.firebasestorage.app',
    iosBundleId: 'com.example.treproject',
  );
}
