// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
  show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _envOrThrow('FIREBASE_ANDROID_API_KEY'),
        appId: _envOrThrow('FIREBASE_ANDROID_APP_ID'),
        messagingSenderId: _envOrThrow('FIREBASE_ANDROID_MESSAGING_SENDER_ID'),
        projectId: _envOrThrow('FIREBASE_ANDROID_PROJECT_ID'),
        storageBucket: _envOrThrow('FIREBASE_ANDROID_STORAGE_BUCKET'),
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _envOrThrow('FIREBASE_IOS_API_KEY'),
        appId: _envOrThrow('FIREBASE_IOS_APP_ID'),
        messagingSenderId: _envOrThrow('FIREBASE_IOS_MESSAGING_SENDER_ID'),
        projectId: _envOrThrow('FIREBASE_IOS_PROJECT_ID'),
        storageBucket: _envOrThrow('FIREBASE_IOS_STORAGE_BUCKET'),
        iosBundleId: _envOrThrow('FIREBASE_IOS_BUNDLE_ID'),
      );

  static String _envOrThrow(String key) {
    final value = dotenv.env[key];
    if (value == null || value.isEmpty) {
      throw StateError('Variável de ambiente "$key" não encontrada ou vazia.');
    }
    return value;
  }
}
